import PyConKenyaReport from "@/components/report";

const scheduleData = [
  {
    date: "May 6, 2024",
    sessions: [
      {
        time: "08:00am - 09:00am",
        title: "Arrival",
        type: "registration",
        speaker: "",
        duration: "60 min",
      },
      {
        time: "09:00am - 09:20am",
        title: "Open remarks",
        type: "opening",
        speaker: "PyCon Kenya Organizers",
        duration: "20 min",
      },
      {
        time: "09:20am - 09:50am",
        title: "Keynote 1",
        type: "keynote",
        speaker: "PyCon Kenya Organizers",
        duration: "30 min",
      },
      {
        time: "09:50am - 10:20am",
        title: "Keynote 2",
        type: "keynote",
        speaker: "PyCon Kenya Organizers",
        duration: "30 min",
      },
      {
        time: "10:20am - 10:50am",
        title: "Keynote 3",
        type: "keynote",
        speaker: "PyCon Kenya Organizers",
        duration: "30 min",
      },
      {
        time: "10:55am - 11:30am",
        title: "Breakout",
        type: "break",
        speaker: "",
        duration: "35 min",
      },
      {
        time: "11:30am - 12:30pm",
        title: "Best Practices for Building With External Apis",
        type: "talk",
        speaker: "Ben Greenberg",
        duration: "60 min",
      },
      {
        time: "11:30am - 12:30pm",
        title: "GraphQL APIs with Django",
        type: "workshop",
        speaker: "Grace Zawadi",
        duration: "60 min",
      },
      {
        time: "11:30am - 12:30pm",
        title: "Deploying your AI model through a flask API",
        type: "workshop",
        speaker: "Irving Amukasa",
        duration: "60 min",
      },
      {
        time: "11:30am - 12:30pm",
        title: "Intro to Web3 development with Python",
        type: "workshop",
        speaker: "Grishon Nganga",
        duration: "60 min",
      },
      {
        time: "11:30am - 12:30pm",
        title: "Introduction to Django",
        type: "talk",
        speaker: "Bethany Jepchumba",
        duration: "60 min",
      },
      {
        time: "11:30am - 12:30pm",
        title: "Big Data Engineering with Python and Apache Spark",
        type: "workshop",
        speaker: "Cyril Michino",
        duration: "60 min",
      },
      {
        time: "12:30pm - 12:45pm",
        title: "Breakout",
        type: "break",
        speaker: "",
        duration: "15 min",
      },
      {
        time: "12:45pm - 01:45pm",
        title: "Containers and environment variables",
        type: "talk",
        speaker: "Thuo Ng'ang'a",
        duration: "60 min",
      },
      {
        time: "12:45pm - 01:45pm",
        title: "Detecting Systematic Deviations in Data and Models",
        type: "talk",
        speaker: "Janice Muia",
        duration: "60 min",
      },
      {
        time: "12:45pm - 01:45pm",
        title: "Using Chaos toolkit to determine resiliency for your web app",
        type: "talk",
        speaker: "Karan Balkar",
        duration: "60 min",
      },
      {
        time: "12:45pm - 01:45pm",
        title: "FastAPI Everything",
        type: "talk",
        speaker: "Collins Muriuki",
        duration: "60 min",
      },
      {
        time: "12:45pm - 01:45pm",
        title: "A Simplified Approach to Deploying ML Apps on a PaaS",
        type: "talk",
        speaker: "Gift Ojeabulu",
        duration: "60 min",
      },
      {
        time: "12:45pm - 01:45pm",
        title:
          "Building AI Text Applications with Mantium's Python client library",
        type: "talk",
        speaker: "Blessing Adesiji",
        duration: "60 min",
      },
      {
        time: "01:45pm - 02:45pm",
        title: "Lunch",
        type: "break",
        speaker: "",
        duration: "60 min",
      },
      {
        time: "02:45pm - 03:45pm",
        title: "Using Python to build on the Twitter API",
        type: "talk",
        speaker: "Velda Kiara",
        duration: "60 min",
      },
      {
        time: "02:45pm - 03:45pm",
        title: "Python in embedded systems",
        type: "workshop",
        speaker: "Jack ogina",
        duration: "60 min",
      },
      {
        time: "02:45pm - 03:45pm",
        title: "Exploring Network Clusters in Python",
        type: "talk",
        speaker: "Anand s",
        duration: "60 min",
      },
      {
        time: "02:45pm - 03:45pm",
        title: "Saving millions of lives with predictive Geo-AI",
        type: "talk",
        speaker: "Sumedh Ghatage",
        duration: "60 min",
      },
      {
        time: "02:45pm - 03:45pm",
        title: "Generative adversarial Network",
        type: "talk",
        speaker: "Mark Mburu Njoroge",
        duration: "60 min",
      },
      {
        time: "02:45pm - 03:45pm",
        title: "Algorithm Selection in Machine Learning",
        type: "talk",
        speaker: "Martin Oywa",
        duration: "60 min",
      },
      {
        time: "03:45pm - 04:00pm",
        title: "Breakout",
        type: "break",
        speaker: "",
        duration: "15 min",
      },
      {
        time: "04:00pm - 05:00pm",
        title: "How to become a Python developer in Kenya",
        type: "talk",
        speaker: "Victor Ashioya",
        duration: "60 min",
      },
      {
        time: "04:00pm - 05:00pm",
        title: "Build a chatbot with Python and open-source models",
        type: "talk",
        speaker: "Alex Muiruri",
        duration: "60 min",
      },
      {
        time: "04:00pm - 05:00pm",
        title: "How I used Python to automate my home",
        type: "talk",
        speaker: "Michael Bukachi",
        duration: "60 min",
      },
      {
        time: "04:00pm - 05:00pm",
        title: "Leveraging Python to Future Prove Data Science Career",
        type: "talk",
        speaker: "Stanley Ndagi",
        duration: "60 min",
      },
      {
        time: "04:00pm - 05:00pm",
        title:
          "Serverless Python Google Cloud Platform: Hosting Django on Cloud Run",
        type: "talk",
        speaker: "Paul Onteri",
        duration: "60 min",
      },
      {
        time: "04:00pm - 05:00pm",
        title:
          "Leveraging Computer Vision with Python to solve real-world problems",
        type: "talk",
        speaker: "Mercy Nyamohanga",
        duration: "60 min",
      },
      {
        time: "05:00pm - 05:30pm",
        title: "Closing Remarks",
        type: "closing",
        speaker: "PyCon Kenya Organizers",
        duration: "30 min",
      },
    ],
  },
  {
    date: "May 7, 2024",
    sessions: [
      {
        time: "08:00am - 09:00am",
        title: "Arrival",
        type: "registration",
        speaker: "",
        duration: "60 min",
      },
      {
        time: "09:00am - 09:20am",
        title: "Propel Session",
        type: "talk",
        speaker: "PyCon Kenya Organizers",
        duration: "20 min",
      },
      {
        time: "09:20am - 09:30am",
        title: "Datakind Session",
        type: "talk",
        speaker: "PyCon Kenya Organizers",
        duration: "10 min",
      },
      {
        time: "09:30am - 10:20am",
        title: "Panel Discussion",
        type: "panel",
        speaker: "PyCon Kenya Organizers",
        duration: "50 min",
      },
      {
        time: "10:20am - 10:50am",
        title: "How to get US Remote Jobs",
        type: "talk",
        speaker: "KelvinSam Onkundi",
        duration: "30 min",
      },
      {
        time: "10:50am - 11:00am",
        title: "Breakout",
        type: "break",
        speaker: "",
        duration: "10 min",
      },
      {
        time: "11:00am - 12:00pm",
        title:
          "Using AI to help mothers in Kenya get the help they need, faster",
        type: "talk",
        speaker: "Jay Patel",
        duration: "60 min",
      },
      {
        time: "11:00am - 12:00pm",
        title: "Securing your Python APIs",
        type: "talk",
        speaker: "Daniel Nduati",
        duration: "60 min",
      },
      {
        time: "11:00am - 12:00pm",
        title: "Getting started with Test Driven Development in Django",
        type: "talk",
        speaker: "Rose Oketch",
        duration: "60 min",
      },
      {
        time: "11:00am - 12:00pm",
        title: "From idea to production with Python",
        type: "talk",
        speaker: "Timothy Matara",
        duration: "60 min",
      },
      {
        time: "11:00am - 12:00pm",
        title: "What's new in Python 3.10",
        type: "talk",
        speaker: "Beverly Anyona",
        duration: "60 min",
      },
      {
        time: "11:00am - 12:00pm",
        title: "Deploying your AI model through a flask API",
        type: "workshop",
        speaker: "Abado Jack Mtulla",
        duration: "60 min",
      },
      {
        time: "12:00pm - 01:00pm",
        title: "Lunch",
        type: "break",
        speaker: "",
        duration: "60 min",
      },
      {
        time: "01:00pm - 02:00pm",
        title: "Django Q and Celery for asynchronous tasks",
        type: "talk",
        speaker: "Kennedy Kanyi",
        duration: "60 min",
      },
      {
        time: "01:00pm - 02:00pm",
        title: "Best Practices for Building With External Apis",
        type: "talk",
        speaker: "Adebayo Oshingbesan",
        duration: "60 min",
      },
      {
        time: "01:00pm - 02:00pm",
        title: "Intro to Web3 development with Python",
        type: "workshop",
        speaker: "Jordan Muthemba",
        duration: "60 min",
      },
      {
        time: "01:00pm - 02:00pm",
        title: "Building CLI Tools with Python",
        type: "talk",
        speaker: "Michael Kimathi",
        duration: "60 min",
      },
      {
        time: "01:00pm - 02:00pm",
        title: "Automating Minecraft with Python Websockets",
        type: "talk",
        speaker: "Anand s",
        duration: "60 min",
      },
      {
        time: "01:00pm - 02:00pm",
        title: "Data Science for beginners",
        type: "talk",
        speaker: "Mwangi Kabiru",
        duration: "60 min",
      },
      {
        time: "02:00pm - 02:15pm",
        title: "Breakout",
        type: "break",
        speaker: "",
        duration: "15 min",
      },
      {
        time: "02:15pm - 03:15pm",
        title: "Generative adversarial Network",
        type: "talk",
        speaker: "Collins Muriuki",
        duration: "60 min",
      },
      {
        time: "02:15pm - 03:15pm",
        title: "A Simplified Approach to Deploying ML Apps on a PaaS",
        type: "talk",
        speaker: "Mwangi Kabiru",
        duration: "60 min",
      },
      {
        time: "02:15pm - 03:15pm",
        title: "Detecting Systematic Deviations in Data and Models",
        type: "talk",
        speaker: "Daniel Nduati",
        duration: "60 min",
      },
      {
        time: "02:15pm - 03:15pm",
        title: "Python for Data Science",
        type: "talk",
        speaker: "Rose Oketch",
        duration: "60 min",
      },
      {
        time: "02:15pm - 03:15pm",
        title: "Using Python to build on the Twitter API",
        type: "talk",
        speaker: "Mercy Nyamohanga",
        duration: "60 min",
      },
      {
        time: "02:15pm - 03:15pm",
        title: "Saving millions of lives with predictive Geo-AI",
        type: "talk",
        speaker: "Billy Gareth",
        duration: "60 min",
      },
      {
        time: "03:15pm - 03:45pm",
        title: "Closing Remarks",
        type: "closing",
        speaker: "PyCon Kenya Organizers",
        duration: "30 min",
      },
    ],
  },
];

const statistics = {
  totalAttendees: 627,
  speakers: 80,
  workshops: 17,
  talks: 63,
  countries: 7,
  companies: 43,
  students: 339,
  professionals: 288,
  distributionByCountry: [
    { country: "Kenya", attendees: 578, percentage: 92.19 },
    { country: "Uganda", attendees: 23, percentage: 3.67 },
    { country: "Tanzania", attendees: 13, percentage: 2.07 },
    { country: "Nigeria", attendees: 9, percentage: 1.44 },
    { country: "Others", attendees: 4, percentage: 0.64 },
  ],
  statisfactionRate: 94,
  recommendationRate: 84,
  retentionRate: 89,
};

const topicDistribution = [
  { topic: "Data Science & ML", percentage: 37.5, count: 30 },
  { topic: "Others", percentage: 25.0, count: 20 },
  { topic: "Web Development", percentage: 15.0, count: 12 },
  { topic: "DevOps & Cloud", percentage: 11.25, count: 9 },
  { topic: "Community & Career", percentage: 7.5, count: 6 },
  { topic: "IoT & Hardware", percentage: 3.75, count: 3 },
];

const images = [
  "/2022-report/DSC_0017-3.jpg",
  "/2022-report/DSC_0022-3.jpg",
  "/2022-report/DSC_0065-2.jpg",
  "/2022-report/DSC_0083-2.jpg",
  "/2022-report/DSC_0086-3.jpg",
  "/2022-report/DSC_0092-3.jpg",
  "/2022-report/DSC_0148-3.jpg",
  "/2022-report/DSC_0202-2.jpg",
  "/2022-report/DSC_0213-2.jpg",
  "/2022-report/DSC_0253-3.jpg",
  "/2022-report/DSC_0270.jpg",
  "/2022-report/DSC_0273-2.jpg",
  "/2022-report/DSC_0278-2.jpg",
  "/2022-report/DSC_0291.jpg",
  "/2022-report/DSC_0308.jpg",
  "/2022-report/DSC_0314-3.jpg",
  "/2022-report/DSC_0317-3.jpg",
  "/2022-report/DSC_0340-2.jpg",
  "/2022-report/DSC_0340-3.jpg",
  "/2022-report/DSC_0356-2.jpg",
  "/2022-report/DSC_0384.jpg",
  "/2022-report/DSC_0388-3.jpg",
  "/2022-report/DSC_0452-4.jpg",
  "/2022-report/DSC_0490-2.jpg",
  "/2022-report/DSC_0519-4.jpg",
  "/2022-report/DSC_0540-4.jpg",
  "/2022-report/DSC_0587.jpg",
  "/2022-report/DSC_0610-3.jpg",
  "/2022-report/DSC_0616-2.jpg",
  "/2022-report/DSC_0623-4.jpg",
  "/2022-report/DSC_0667-2.jpg",
  "/2022-report/DSC_0690.jpg",
  "/2022-report/DSC_0740-4.jpg",
  "/2022-report/DSC_0766-5.jpg",
  "/2022-report/DSC_0778-3.jpg",
  "/2022-report/DSC_0803.jpg",
  "/2022-report/DSC_0804-2.jpg",
  "/2022-report/DSC_0890-4.jpg",
  "/2022-report/DSC_0926-2.jpg",
  "/2022-report/DSC_0927.jpg",
  "/2022-report/DSC_0957.jpg",
  "/2022-report/DSC_0966-2.jpg",
  "/2022-report/DSC_0985-2.jpg",
  "/2022-report/DSC_0988-3.jpg",
  "/2022-report/DSC_1003.jpg",
];

export default function Page() {
  return (
    <PyConKenyaReport
      year={2022}
      date="May 6-7, 2024"
      venue="United States International University, Nairobi, Kenya"
      schedule={scheduleData}
      statistics={statistics}
      topicDistribution={topicDistribution}
      images={images}
    />
  );
}
